### ISSUE TITLE
Allow annotation level to be configured for Github Action

### ISSUE THREAD

**Issue by colincadams** [nightfallai/jenkins_test#71]
Currently, findings are always reported in the github action as `failure` level findings. This is hardcoded here: https://github.com/nightfallai/nightfall_code_scanner/blob/92a6b9ab2e9e93a83cb5a6d8179d370813d1a64e/internal/clients/diffreviewer/github/github_service.go#L37

We would like to pilot this action running on our PRs, with the findings reported at a `notice` or `warning` level. This will make the tool slightly less noisy while we evaluate the false positive rate internally and fine tune our configuration.

It would be great if you supported configuring the level that findings should be reported for your github action. From our perspective it would be useful either in the github workflow configuration itself:

```
      - name: Checkout Repo Action
        uses: actions/checkout@v2

      - name: nightfallDLP action step
        uses: nightfallai/nightfall_dlp_action@v2.0.2
        env:
          NIGHTFALL_API_KEY: ${{ secrets.NIGHTFALL_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_BEFORE: ${{ github.event.before }}
          ANNOTATION_LEVEL: warning
```

or secondarily as a separate entry in the `.nightfalldlp/config.json`. If in the nightfall config, then it might be a little strange unless this is promoted to a full nightfall level concept. The advantage would be it could be configured at a per detection rule level, but this greatly increases the scope of this ticket.

For reference, these are the supported levels ([docs](https://docs.github.com/en/rest/reference/checks)): 
<img width="806" alt="Screen Shot 2022-04-15 at 10 47 59 AM" src="https://user-images.githubusercontent.com/3762913/163603830-66e80258-4ff6-41c3-b44b-d231d3e7bfc3.png">
